Repository veritrans/veritrans-android, pull requests merged in 2018-02, with the labels that each got.

#504 Chore/update gopay qr instruction
  demo/src/main/java/com/midtrans/demo/AppUtils.java
  uikit/src/main/java/com/midtrans/sdk/uikit/activities/PaymentMethodsActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/utilities/TimeUtils.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/gopay/status/GoPayStatusActivity.java
  uikit/src/main/res/drawable-hdpi/ic_gopay_qr.png
  uikit/src/main/res/drawable-hdpi/ic_gopay_scan.png
  uikit/src/main/res/drawable-mdpi/ic_gopay_qr.png
  uikit/src/main/res/drawable-mdpi/ic_gopay_scan.png
  uikit/src/main/res/drawable-xhdpi/ic_gopay_qr.png
  uikit/src/main/res/drawable-xhdpi/ic_gopay_scan.png
  uikit/src/main/res/drawable-xxhdpi/ic_gopay_qr.png
  uikit/src/main/res/drawable-xxhdpi/ic_gopay_scan.png
  uikit/src/main/res/drawable-xxxhdpi/ic_gopay_qr.png
  uikit/src/main/res/drawable-xxxhdpi/ic_gopay_scan.png
  uikit/src/main/res/layout/layout_gopay_payment_tablet.xml
  uikit/src/main/res/layout/layout_gopay_status_tablet.xml
  uikit/src/main/res/values-in/strings.xml
  uikit/src/main/res/values/strings.xml
Labels: enhancement

#506 Fixed minus amount in BNI Point
  uikit/src/main/java/com/midtrans/sdk/uikit/views/creditcard/bankpoints/BankPointsActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/creditcard/bankpoints/BankPointsPresenter.java
Labels: bug

#507 Bug/minus bank point
  .bmp.yml
  corekit/build.gradle
  demo/build.gradle
  demo/src/main/java/com/midtrans/demo/AppUtils.java
  scancard/build.gradle
  uikit/build.gradle
  uikit/src/main/java/com/midtrans/sdk/uikit/activities/PaymentMethodsActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/utilities/TimeUtils.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/creditcard/bankpoints/BankPointsActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/creditcard/bankpoints/BankPointsPresenter.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/gopay/status/GoPayStatusActivity.java
  uikit/src/main/res/drawable-hdpi/ic_gopay_qr.png
  uikit/src/main/res/drawable-hdpi/ic_gopay_scan.png
  uikit/src/main/res/drawable-mdpi/ic_gopay_qr.png
  uikit/src/main/res/drawable-mdpi/ic_gopay_scan.png
  uikit/src/main/res/drawable-xhdpi/ic_gopay_qr.png
  uikit/src/main/res/drawable-xhdpi/ic_gopay_scan.png
  uikit/src/main/res/drawable-xxhdpi/ic_gopay_qr.png
  uikit/src/main/res/drawable-xxhdpi/ic_gopay_scan.png
  uikit/src/main/res/drawable-xxxhdpi/ic_gopay_qr.png
  uikit/src/main/res/drawable-xxxhdpi/ic_gopay_scan.png
  uikit/src/main/res/layout/layout_gopay_payment_tablet.xml
  uikit/src/main/res/layout/layout_gopay_status_tablet.xml
  uikit/src/main/res/values-in/strings.xml
  uikit/src/main/res/values/strings.xml
Labels: Release

#508 finish tnc bni point
  uikit/src/main/AndroidManifest.xml
  uikit/src/main/java/com/midtrans/sdk/uikit/views/creditcard/details/CreditCardDetailsActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/creditcard/tnc/TermsAndConditionsActivity.java
  uikit/src/main/res/layout/activity_tnc.xml
  uikit/src/main/res/layout/layout_tnc_bni_point.xml
  uikit/src/main/res/values-in/strings.xml
  uikit/src/main/res/values/colors.xml
  uikit/src/main/res/values/strings.xml
Labels: enhancement

#509 Changed CC detail page title to "Card details"
  .gitignore
  uikit/src/main/java/com/midtrans/sdk/uikit/views/creditcard/details/CreditCardDetailsActivity.java
Labels: enhancement

#510 Release 1.15.3
  .bmp.yml
  .gitignore
  corekit/build.gradle
  scancard/build.gradle
  sdk-example/src/main/java/com/midtrans/sdk/sample/MainActivity.java
  uikit/build.gradle
  uikit/src/main/AndroidManifest.xml
  uikit/src/main/assets/bank_bins.json
  uikit/src/main/java/com/midtrans/sdk/uikit/activities/PaymentMethodsActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/activities/UserDetailsActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/fragments/UserAddressFragment.java
  uikit/src/main/java/com/midtrans/sdk/uikit/utilities/SdkUIFlowUtil.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/creditcard/details/CreditCardDetailsActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/creditcard/tnc/TermsAndConditionsActivity.java
  uikit/src/main/res/layout/activity_tnc.xml
  uikit/src/main/res/layout/layout_tnc_bni_point.xml
  uikit/src/main/res/values-in/strings.xml
  uikit/src/main/res/values/colors.xml
  uikit/src/main/res/values/strings.xml
Labels: Release, bug, enhancement

#512 Put some delay before hide loading indicator
  uikit/src/main/java/com/midtrans/sdk/uikit/abstracts/BaseActivity.java
Labels: enhancement
