Repository veritrans/veritrans-android, pull requests merged in 2018-03, with the labels that each got.

#513 Story/1483 add blacklist
  .bmp.yml
  corekit/build.gradle
  corekit/src/main/res/values-in/strings.xml
  corekit/src/main/res/values/strings.xml
  demo/src/main/java/com/midtrans/demo/DemoConfigActivity.java
  scancard/build.gradle
  uikit/build.gradle
  uikit/src/main/java/com/midtrans/sdk/uikit/activities/UserDetailsActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/models/CreditCardTransaction.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/creditcard/details/CreditCardDetailsActivity.java
  uikit/src/main/res/values-in/strings.xml
  uikit/src/main/res/values/strings.xml
Labels: enhancement, feature

#514 Added validation so BNI Point T&C only triggered when user use BNI card
  uikit/src/main/java/com/midtrans/sdk/uikit/views/creditcard/details/CreditCardDetailsActivity.java
Labels: bug

#515 Fixed SDK misbehaviour when faced on-low-memory situation in Samsung
  corekit/src/main/java/com/midtrans/sdk/corekit/core/MidtransSDK.java
Labels: bug

#516 Chore/rewording instructions
  corekit/src/main/java/com/midtrans/sdk/corekit/core/MidtransRestAdapter.java
  corekit/src/main/java/com/midtrans/sdk/corekit/utilities/Utils.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/creditcard/details/CreditCardDetailsActivity.java
  uikit/src/main/res/drawable-hdpi/ic_gopay_qr.png
  uikit/src/main/res/drawable-mdpi/ic_gopay_qr.png
  uikit/src/main/res/drawable-xhdpi/ic_gopay_qr.png
  uikit/src/main/res/drawable-xxhdpi/ic_gopay_qr.png
  uikit/src/main/res/drawable-xxxhdpi/ic_gopay_qr.png
  uikit/src/main/res/values-in/strings.xml
  uikit/src/main/res/values/strings.xml
Labels: enhancement

#517 Chor/refine cc field
  uikit/src/main/java/com/midtrans/sdk/uikit/views/creditcard/details/CreditCardDetailsActivity.java
Labels: bug

#520 wrong info displayed on danamon online when payment has been processed
  uikit/src/main/java/com/midtrans/sdk/uikit/utilities/UiKitConstants.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/status/PaymentStatusActivity.java
  uikit/src/main/res/values-in/strings.xml
  uikit/src/main/res/values/strings.xml
Labels: bug

#523 Release 1.17.0
  .bmp.yml
  corekit/build.gradle
  corekit/src/main/java/com/midtrans/sdk/corekit/core/MidtransRestAPI.java
  corekit/src/main/java/com/midtrans/sdk/corekit/core/MidtransRestAdapter.java
  corekit/src/main/java/com/midtrans/sdk/corekit/core/MidtransSDK.java
  corekit/src/main/java/com/midtrans/sdk/corekit/core/SdkUtil.java
  corekit/src/main/java/com/midtrans/sdk/corekit/core/SnapTransactionManager.java
  corekit/src/main/java/com/midtrans/sdk/corekit/models/ItemDetails.java
  corekit/src/main/java/com/midtrans/sdk/corekit/models/PaymentDetails.java
  corekit/src/main/java/com/midtrans/sdk/corekit/models/PaymentMethodsModel.java
  corekit/src/main/java/com/midtrans/sdk/corekit/models/promo/Promo.java
  corekit/src/main/java/com/midtrans/sdk/corekit/models/promo/PromoDetails.java
  corekit/src/main/java/com/midtrans/sdk/corekit/models/snap/CreditCardPaymentModel.java
  corekit/src/main/java/com/midtrans/sdk/corekit/models/snap/ItemDetails.java
  corekit/src/main/java/com/midtrans/sdk/corekit/models/snap/Transaction.java
  corekit/src/main/java/com/midtrans/sdk/corekit/models/snap/params/PromoDetails.java
  corekit/src/main/java/com/midtrans/sdk/corekit/utilities/Utils.java
  corekit/src/main/res/values/colors.xml
  corekit/src/test/java/com/midtrans/sdk/corekit/core/SnapTransactionManagerTest.java
  corekit/src/test/java/com/midtrans/sdk/corekit/models/snap/ItemDetailsTest.java
  demo/build.gradle
  demo/src/main/java/com/midtrans/demo/AppUtils.java
  demo/src/main/java/com/midtrans/demo/DemoConfigActivity.java
  scancard/build.gradle
  sdk-example/src/main/java/com/midtrans/sdk/sample/MainActivity.java
  uikit/build.gradle
  uikit/src/main/java/com/midtrans/sdk/uikit/PaymentMethods.java
  uikit/src/main/java/com/midtrans/sdk/uikit/UIFlow.java
  uikit/src/main/java/com/midtrans/sdk/uikit/abstracts/BaseActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/abstracts/BasePaymentActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/activities/BaseActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/activities/PaymentMethodsActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/activities/UserDetailsActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/adapters/PaymentMethodsAdapter.java
  uikit/src/main/java/com/midtrans/sdk/uikit/adapters/TransactionDetailsAdapter.java
  uikit/src/main/java/com/midtrans/sdk/uikit/models/CreditCardTransaction.java
  uikit/src/main/java/com/midtrans/sdk/uikit/utilities/MessageUtil.java
  uikit/src/main/java/com/midtrans/sdk/uikit/utilities/UiKitConstants.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/creditcard/bankpoints/BankPointsActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/creditcard/bankpoints/BankPointsPresenter.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/creditcard/details/CreditCardDetailsActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/creditcard/details/CreditCardDetailsPresenter.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/creditcard/details/PromosAdapter.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/creditcard/saved/SavedCreditCardActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/status/PaymentStatusActivity.java
  uikit/src/main/res/drawable-hdpi/ic_gopay_qr.png
  uikit/src/main/res/drawable-mdpi/ic_gopay_qr.png
  uikit/src/main/res/drawable-xhdpi/ic_gopay_qr.png
  uikit/src/main/res/drawable-xxhdpi/ic_gopay_qr.png
  uikit/src/main/res/drawable-xxxhdpi/ic_gopay_qr.png
  uikit/src/main/res/layout/activity_payment_status.xml
  uikit/src/main/res/layout/layout_credit_card_form.xml
  uikit/src/main/res/layout/layout_row_payment_methods.xml
  uikit/src/main/res/layout/layout_row_promos.xml
  uikit/src/main/res/values-in/strings.xml
  uikit/src/main/res/values/strings.xml
Labels: Release, enhancement

#521 Chor/disallow backup local data
  corekit/build.gradle
  corekit/proguard-rules.pro
  corekit/src/main/AndroidManifest.xml
  corekit/src/main/java/com/midtrans/sdk/corekit/core/Constants.java
  corekit/src/main/java/com/midtrans/sdk/corekit/core/MidtransSDK.java
  corekit/src/main/java/com/midtrans/sdk/corekit/core/PaymentType.java
  corekit/src/main/java/com/midtrans/sdk/corekit/core/SdkUtil.java
  corekit/src/test/java/com/midtrans/sdk/corekit/APIClientMain.java
  corekit/src/test/java/com/midtrans/sdk/corekit/core/MidtransAndroidSDKTest.java
  corekit/src/test/java/com/midtrans/sdk/corekit/core/SDKUtilsTest.java
  corekit/src/test/java/com/midtrans/sdk/corekit/core/SnapTransactionManagerTest.java
  demo/src/main/AndroidManifest.xml
  sdk-example/src/main/AndroidManifest.xml
  uikit/proguard-rules.pro
  uikit/src/main/AndroidManifest.xml
  uikit/src/main/java/com/midtrans/sdk/uikit/activities/PaymentMethodsActivity.java
Labels: enhancement

#522 Chore/prevent log leak
  circle.yml
  corekit/build.gradle
  corekit/src/main/java/com/midtrans/sdk/corekit/core/MidtransSDK.java
  demo/src/main/java/com/midtrans/demo/AppUtils.java
  demo/src/main/java/com/midtrans/demo/DemoCardRegisterActivity.java
  demo/src/main/java/com/midtrans/demo/DemoOrderReviewActivity.java
  demo/src/main/java/com/midtrans/demo/InstallmentDialogFragment.java
  demo/src/main/java/com/midtrans/demo/SelectPaymentMethodDialogFragment.java
  demo/src/main/java/com/midtrans/demo/widgets/Utils.java
  scancard/src/main/java/com/midtrans/sdk/scancard/ScanCardActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/UIFlow.java
  uikit/src/main/java/com/midtrans/sdk/uikit/abstracts/BaseActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/abstracts/BasePaymentActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/activities/BaseActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/activities/IndosatDompetkuActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/activities/MandiriClickPayActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/activities/PaymentMethodsActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/activities/PaymentWebActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/activities/SelectBankTransferActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/activities/UserDetailsActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/adapters/TransactionDetailsAdapter.java
  uikit/src/main/java/com/midtrans/sdk/uikit/fragments/CardDetailsFragment.java
  uikit/src/main/java/com/midtrans/sdk/uikit/fragments/WebviewFragment.java
  uikit/src/main/java/com/midtrans/sdk/uikit/utilities/DeviceUtils.java
  uikit/src/main/java/com/midtrans/sdk/uikit/utilities/MessageUtil.java
  uikit/src/main/java/com/midtrans/sdk/uikit/utilities/SdkUIFlowUtil.java
  uikit/src/main/java/com/midtrans/sdk/uikit/utilities/WidgetUtils.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/banktransfer/instruction/InstructionBcaVaFragment.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/creditcard/register/CardRegistrationActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/creditcard/saved/SavedCreditCardPresenter.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/creditcard/tnc/TermsAndConditionsActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/mandiri_clickpay/MandiriClickPayActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/status/PaymentStatusActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/webview/WebViewPaymentActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/widgets/Utils.java
  widgets/src/main/java/com/midtrans/sdk/widgets/CreditCardForm.java
Labels: enhancement

#518 change glide to ion
  uikit/build.gradle
  uikit/proguard-rules.pro
  uikit/src/main/java/com/midtrans/sdk/uikit/abstracts/BaseActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/abstracts/BasePaymentActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/activities/BaseActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/activities/PaymentMethodsActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/utilities/SdkUIFlowUtil.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/gopay/status/GoPayStatusActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/widgets/MidtransProgressDialogFragment.java
Labels: enhancement

#524 Chore/prefs with password
  build.gradle
  corekit/build.gradle
  corekit/src/main/java/com/midtrans/sdk/corekit/core/SdkUtil.java
  environmentSetup.sh
Labels: bug

#525 - ghost buster
  corekit/src/main/java/com/midtrans/sdk/corekit/models/TransactionResponse.java
  corekit/src/main/res/values-in/strings.xml
  corekit/src/main/res/values/strings.xml
  uikit/src/main/java/com/midtrans/sdk/uikit/abstracts/BaseActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/abstracts/BaseVaPaymentStatusActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/activities/PaymentMethodsActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/banktransfer/payment/BankTransferPaymentActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/creditcard/saved/SavedCreditCardActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/gopay/status/GoPayStatusActivity.java
  uikit/src/main/java/com/midtrans/sdk/uikit/views/status/PaymentStatusActivity.java
  uikit/src/main/res/layout/fragment_instruction_bca_transfer_mbca.xml
  uikit/src/main/res/values-in/strings.xml
  uikit/src/main/res/values/strings.xml
Labels: bug, enhancement
